select * from customer
--1)	What is the total revenue generated by male Vs female customers?
select gender, sum(purchase_amount) as revenue
from customer
group by gender

--2)	Which customer used a discount but still spent more than the average purchase amount?
select customer_id, purchase_amount from customer
where customer.purchase_amount > (select avg(purchase_amount) from customer) and discount_applied = 'Yes'

--3)	Which are the top 5 products with the highest average review rating?

select item_purchased,category,ROUND(avg(review_rating::numeric),2) as avg_rating from customer
group by customer.item_purchased, customer.category
order by avg(review_rating) desc
limit 5

--select item_purchased,category,review_rating from customer
--where customer.review_rating > (select avg(review_rating) from customer)
--group by customer.item_purchased, customer.category, customer.review_rating
--order by avg(review_rating) desc
--limit 5;
select * from customer

--4)	Compare the average purchase amounts between standard and express shipping

select shipping_type,round(avg(purchase_amount),2) from customer
where shipping_type ='Express' or shipping_type='Standard'
group by shipping_type

--OR

select shipping_type, round(avg(purchase_amount),2) from customer
where shipping_type in ('Express','Standard')
group by shipping_type


--5)	Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
select subscription_status,count(customer_id),round(sum(purchase_amount),2) as total_revenu, round(avg(purchase_amount),2) as average_spend from customer
group by subscription_status
order by total_revenu

--6)	Which 4 products have the highest percentage of purchases with discounts applied?

select item_purchased, 100*sum(case when discount_applied ='Yes' then 1 else 0 end)/count(*) as discount_rate
from customer
group by item_purchased
order by discount_rate desc
limit 4


select * from customer
--7)	Segment customers into New, Returning and loyal based on their total number of previous purchases and show the count of each segment.

with customer_type as(
select customer_id,previous_purchases,
CASE 
	When previous_purchases =1 then 'New'
	When previous_purchases Between 2 and 10 then 'Returning'
	ELSE 'Loyal'
END as customer_segment
from customer
)
select customer_segment,count(*) as "Number of Customers"
from customer_type
group by customer_segment


select * from customer
--8)	What are the top 3 most purchased products within each category?

with item_count as (
select category,item_purchased,row_number() over(partition by category order by count(customer_id) desc) as item_rank,count(customer_id) as total_orders
from customer
group by category, item_purchased)

select item_rank,category, item_purchased, total_orders
from item_count
where item_rank<=3

--9)	Are customers who are repeat buyers(more than 5 previous purchases) also likely to subscribe?
select count(customer_id) as cust_sub, subscription_status from customer
where previous_purchases >5 
group by subscription_status

--10)	What is the revenue contribution of each age group?

select age_group,sum(purchase_amount) as revenu from customer
group by age_group


